import React, { createContext, useContext, useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';
import { useAuth } from './AuthContext';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // ── Navigation ──
    'nav.dashboard': 'Dashboard',
    'nav.fleetOverview': 'Fleet Overview',
    'nav.vessels': 'Vessels',
    'nav.equipment': 'Equipment',
    'nav.waterToys': 'Water Toys',
    'nav.maintenance': 'Maintenance',
    'nav.inventory': 'Inventory',
    'nav.manuals': 'Documents',
    'nav.history': 'History',
    'nav.customers': 'Customers',
    'nav.users': 'Users',
    'nav.fuel': 'Fuel & Consumables',
    'nav.costs': 'Cost Overview',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.needHelp': 'Need Help?',
    'nav.contactSupport': 'Contact support for assistance',
    'nav.close': 'Close menu',
    'nav.onboardingSubmissions': 'Submissions',
    'nav.compliance' : 'Compliance',
    'nav.budget' : 'Budget',
     'nav.financials' : 'Financials',
     'nav.crew' : 'Crew',
     'nav.guestList' : 'Guest List',
     'nav.procurement' : 'Procurement',

    // ── Header ──
    'header.toggleMenu': 'Toggle menu',
    'header.switchVessel': 'Switch Vessel',
    'header.notifications': 'Notifications',
    'header.logout': 'Logout',

    // ── Login ──
    'login.subtitle': 'Engineering Suite',
    'login.welcome': 'Welcome Back',
    'login.email': 'Email Address',
    'login.emailPlaceholder': 'Enter your email',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.invalidCredentials': 'Invalid email or password',
    'login.error': 'An error occurred. Please try again.',
    'login.signIn': 'Log In',
    'login.signingIn': 'Logging in...',
    'login.demoAccounts': 'Demo Accounts',
    'login.masterAdmin': 'Master Admin',
    'login.customerAdmin': 'Customer Admin',
    'login.engineer': 'Engineer',
    'login.demoPassword': 'Password: demo123',

    // ── Common ──
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.search': 'Search...',
    'common.add': 'Add',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.open': 'Open',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.tryAgain': 'Try Again',
    'common.saveChanges': 'Save Changes',
    'common.noResults': 'No results found',
    'common.showing': 'Showing',
    'common.filters': 'Filters',
    'common.allVessels': 'All Vessels',
    'common.allDepartments': 'All Departments',
    'common.vessel': 'Vessel',
    'common.equipment': 'Equipment',
    'common.actions': 'Actions',
    'common.name': 'Name',
    'common.type': 'Type',
    'common.status': 'Status',
    'common.notes': 'Notes',
    'common.description': 'Description',
    'common.date': 'Date',
    'common.by': 'By',
    'common.unknown': 'Unknown',
    'common.operational': 'Operational',
    'common.critical': 'Critical',
    'common.high': 'High',
    'common.medium': 'Medium',
    'common.low': 'Low',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.you': 'You',
    'common.exportPDF': 'Export PDF',
    'common.noFile': 'No File',
    'common.photos': 'Photos',
    'common.quantity': 'Quantity',
    'common.reason': 'Reason',
    'common.supplier': 'Supplier',
    'common.location': 'Location',
    'common.unit': 'Unit',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.contactSupport': 'Contact Support',
    'common.needHelp': 'Need Help?',
    'common.noData': 'No data available',

    // ── Dashboard ──
    'dashboard.title': 'Dashboard',
    'dashboard.masterTitle': 'Master Admin Dashboard',
    'dashboard.masterSubtitle': 'Platform overview and customer management',
    'dashboard.masterAdmin': 'Master Administrator',
    'dashboard.totalCustomers': 'Total Customers',
    'dashboard.activeSubscriptions': 'Active Subscriptions',
    'dashboard.inTrial': 'in trial',
    'dashboard.trialAccounts': 'Trial Accounts',
    'dashboard.pendingConversion': 'Pending conversion',
    'dashboard.inactiveAccounts': 'Inactive Accounts',
    'dashboard.churned': 'Churned',
    'dashboard.allAccounts': 'All accounts',
    'dashboard.recentCustomers': 'Recent Customers',
    'dashboard.viewAllCustomers': 'View All Customers',
    'dashboard.noCustomersYet': 'No customers yet',
    'dashboard.addFirstCustomer': 'Add First Customer',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.managePlatform': 'Manage your platform efficiently',
    'dashboard.addNewCustomer': 'Add New Customer',
    'dashboard.createUserAccount': 'Create User Account',
    'dashboard.platformInfo': 'Platform Information',
    'dashboard.systemOverview': 'System overview',
    'dashboard.platformStatus': 'Platform Status',
    'dashboard.customerRetention': 'Customer Retention',
    'dashboard.vesselLimit': 'Vessel Limit',
    'dashboard.vesselStatus': 'Vessel Status',
    'dashboard.maintenance': 'Maintenance',
    'dashboard.inventory': 'Inventory',
    'dashboard.attentionNeeded': 'Attention Needed',
    'dashboard.actionRequired': 'ACTION REQUIRED',
    'dashboard.due48h': 'Due 48h',
    'dashboard.outStock': 'Out Stock',
    'dashboard.resolveNow': 'Resolve Now',
    'dashboard.overdueTasks': 'Overdue Tasks',
    'dashboard.dueSoon': 'Due Soon',
    'dashboard.upcoming': 'Upcoming',
    'dashboard.lowStockItems': 'Low Stock Items',
    'dashboard.reorderNeeded': 'Reorder needed',
    'dashboard.allCaughtUp': 'All caught up!',
    'dashboard.urgentMaintenance': 'Urgent Maintenance',
    'dashboard.viewAll': 'View All',
    'dashboard.lowStockAlerts': 'Low Stock Alerts',
    'dashboard.allItemsInStock': 'All items in stock',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.noRecentActivity': 'No recent activity',
    'dashboard.overview': 'Fleet Overview',
    'dashboard.totalVessels': 'Total Vessels',
    'dashboard.activeVessels': 'Active Vessels',
    'dashboard.underMaintenance': 'Under Maintenance',
    'dashboard.docked': 'Docked',
    'dashboard.upcomingMaintenance': 'Upcoming Maintenance',
    'dashboard.dueDate': 'Due Date',

    // ── Vessels ──
    'vessels.title': 'Vessel Management',
    'vessels.subtitle': 'Manage fleet vessels and configurations',
    'vessels.addVessel': 'Add Vessel',
    'vessels.search': 'Search vessels...',
    'vessels.allTypes': 'All Types',
    'vessels.loading': 'Loading vessels...',
    'vessels.errorLoading': 'Error Loading Vessels',
    'vessels.notFound': 'No vessels found',
    'vessels.createdWithCustomers': 'Vessels are created when adding Yacht Owner customers',
    'vessels.adjustFilters': 'Try adjusting your search or filter',
    'vessels.registrationId': 'Registration ID',
    'vessels.yearBuilt': 'Year Built',
    'vessels.loa': 'LOA',
    'vessels.flag': 'Flag',
    'vessels.name': 'Name',
    'vessels.type': 'Type',
    'vessels.captain': 'Captain',
    'vessels.lastInspection': 'Last Inspection',

    // ── Equipment ──
    'equipment.title': 'Equipment Management',
    'equipment.subtitle': 'Manage vessel equipment and systems',
    'equipment.addNew': 'Add Equipment',
    'equipment.search': 'Search equipment...',
    'equipment.searchPlaceholder': 'Search by name, type, manufacturer...',
    'equipment.allTypes': 'All Types',
    'equipment.allManufacturers': 'All Manufacturers',
    'equipment.allVessels': 'All Vessels',
    'equipment.showing': 'Showing',
    'equipment.item': 'item',
    'equipment.items': 'items',
    'equipment.editEquipment': 'Edit equipment',
    'equipment.name': 'Equipment Name',
    'equipment.type': 'Type',
    'equipment.manufacturer': 'Manufacturer',
    'equipment.model': 'Model',
    'equipment.serialNumber': 'Serial Number',
    'equipment.location': 'Location',
    'equipment.vessel': 'Vessel',
    'equipment.notFound': 'No equipment found',
    'equipment.adjustFilters': 'Try adjusting your filters',
    'equipment.installationDate': 'Installation Date',
    'equipment.specifications': 'Specifications',
    'equipment.addEquipment': 'Add Equipment',
    'equipment.lastMaintenance': 'Last Maintenance',
    'equipment.noEquipment': 'No equipment found',
    'equipment.noEquipmentDesc': 'Add equipment to start tracking your vessel systems',
    'equipment.viewTasks': 'View Tasks',
    'equipment.viewManuals': 'View Manuals',
    'equipment.deleteTitle': 'Delete Equipment',
    'equipment.deleteMessage': 'Are you sure you want to delete this equipment? This action cannot be undone.',
    'equipment.editTitle': 'Edit Equipment',
    'equipment.addTitle': 'Add Equipment',
    'equipment.notes': 'Notes',
    'equipment.addHint': 'Fill in the details to add this equipment to your vessel',

    // ── Maintenance ──
    'maintenance.title': 'Maintenance Tasks',
    'maintenance.subtitle': 'Manage preventive maintenance schedule',
    'maintenance.newTask': 'New Task',
    'maintenance.createTask': 'Create New Maintenance Task',
    'maintenance.search': 'Search tasks...',
    'maintenance.allStatus': 'All Status',
    'maintenance.overdue': 'Overdue',
    'maintenance.dueSoon': 'Due Soon',
    'maintenance.upcoming': 'Upcoming',
    'maintenance.completed': 'Completed',
    'maintenance.allPriorities': 'All Priorities',
    'maintenance.allCategories': 'All Categories',
    'maintenance.allVessels': 'All Vessels',
    'maintenance.showing': 'Showing',
    'maintenance.task': 'task',
    'maintenance.tasks': 'tasks',
    'maintenance.notFound': 'No maintenance tasks found',
    'maintenance.equipmentLabel': 'Equipment:',
    'maintenance.vesselLabel': 'Vessel:',
    'maintenance.assignedLabel': 'Assigned:',
    'maintenance.dOverdue': 'd overdue',
    'maintenance.dRemaining': 'd remaining',
    'maintenance.urgent': 'URGENT',
    'maintenance.dueDate': 'Due Date',
    'maintenance.assignee': 'Assignee',
    'maintenance.priority': 'Priority',
    'maintenance.pending': 'Pending',
    'maintenance.inProgress': 'In Progress',
    'maintenance.all': 'All',
    'maintenance.taskTitle': 'Task Title',
    'maintenance.taskTitlePlaceholder': 'e.g., Main Engine Oil Change',
    'maintenance.descriptionPlaceholder': 'Detailed description of the maintenance task...',
    'maintenance.category': 'Category',
    'maintenance.categoryPlaceholder': 'Select or type a category...',
    'maintenance.selectVessel': 'Select Vessel',
    'maintenance.selectEquipment': 'Select Equipment',
    'maintenance.assignedTo': 'Assigned To',
    'maintenance.unassigned': 'Unassigned',
    'maintenance.nextDueDate': 'Next Due Date',
    'maintenance.recurrenceInterval': 'Recurrence Interval',
    'maintenance.taskScheduleNote': 'This task will be added to the maintenance schedule. You can edit it later from the task detail view.',
    'maintenance.createTask2': 'Create Task',
    'maintenance.noEquipment': 'No Equipment',
    'maintenance.status': 'Status',
    'maintenance.completeTask': 'Complete Task',
    'maintenance.completedBy': 'Completed By',
    'maintenance.commentsLabel': 'Comments / Observations',
    'maintenance.commentsPlaceholder': 'Describe the work performed and any observations...',
    'maintenance.issuesDetected': 'Issues Detected (Optional)',
    'maintenance.issuesPlaceholder': 'Describe any issues or concerns found during maintenance...',
    'maintenance.externalServiceCost': 'External Service Cost (Optional)',
    'maintenance.externalServiceCostHint': 'Cost of external technician or service provider, if applicable',
    'maintenance.partsUsed': 'Parts & Consumables Used',
    'maintenance.addItem': 'Add item',
    'maintenance.noPartsAdded': 'No parts or consumables added',
    'maintenance.available': 'Available:',
    'maintenance.exceedsStock': 'exceeds stock',
    'maintenance.photoUploads': 'Photo Uploads (Optional)',
    'maintenance.clickToAddPhotos': 'Click to add photos',
    'maintenance.photoFormats': 'PNG, JPG, WEBP up to 10MB each',
    'maintenance.confirmCompletion': 'Confirm Task Completion',
    'maintenance.confirmCompletionText': 'I confirm that this maintenance task has been completed successfully. Stock will be automatically deducted for',
    'maintenance.uploadingPhotos': 'Uploading photos...',
    'maintenance.completeTaskBtn': 'Complete Task',

    // ── Inventory ──
    'inventory.title': 'Inventory Management',
    'inventory.subtitle': 'Track spare parts and consumables',
    'inventory.addItem': 'Add Item',
    'inventory.allItems': 'All Items',
    'inventory.locationsQR': 'Locations & QR',
    'inventory.lowStockAlert': 'Low Stock Alert',
    'inventory.reorderRecommended': 'Reorder recommended',
    'inventory.showAll': 'Show All',
    'inventory.viewLowStock': 'View Low Stock',
    'inventory.search': 'Search inventory...',
    'inventory.allTypes': 'All Types',
    'inventory.spareParts': 'Spare Parts',
    'inventory.consumables': 'Consumables',
    'inventory.allCategories': 'All Categories',
    'inventory.showing': 'Showing',
    'inventory.item': 'item',
    'inventory.items': 'items',
    'inventory.itemName': 'Item Name',
    'inventory.partNumber': 'Part Number',
    'inventory.category': 'Category',
    'inventory.currentStock': 'Current Stock',
    'inventory.minStock': 'Min Stock',
    'inventory.lowStock': 'Low Stock',
    'inventory.inStock': 'In Stock',
    'inventory.adjust': 'Adjust',
    'inventory.notFound': 'No inventory items found',
    'inventory.unitOfMeasure': 'Unit of Measure',
    'inventory.unitCost': 'Unit Cost',
    'inventory.storageLocation': 'Storage Location',
    'inventory.serialNumber': 'Serial Number',
    'inventory.sparePart': 'Spare Part',
    'inventory.consumable': 'Consumable',
    'inventory.quantity': 'Quantity',
    'inventory.saveItem': 'Save Item',
    'inventory.itemDetails': 'Item Details',
    'inventory.supplierInfo': 'Supplier Information',
    'inventory.supplierName': 'Supplier Name',
    'inventory.sendReorderRequest': 'Send Reorder Request',
    'inventory.stockMovementHistory': 'Stock Movement History',
    'inventory.stockAdded': 'Stock Added',
    'inventory.stockRemoved': 'Stock Removed',
    'inventory.adjustment': 'Adjustment',
    'inventory.stockStatus': 'Stock Status',
    'inventory.lowStockReorder': 'Low Stock - Reorder Needed',
    'inventory.locationQR': 'Location QR',
    'inventory.viewDetails': 'View Details',
    'inventory.associatedEquipment': 'Associated Equipment',
    'inventory.quickActions': 'Quick Actions',
    'inventory.addStock': 'Add Stock',
    'inventory.recordUsage': 'Record Usage',
    'inventory.contactSupplier': 'Contact Supplier',
    'inventory.adjustStock': 'Adjust Stock',
    'inventory.adjustmentType': 'Adjustment Type',
    'inventory.setLevel': 'Set',
    'inventory.newStockLevel': 'New Stock Level',
    'inventory.storageLocations': 'Storage Locations',
    'inventory.locationSearch': 'Search locations...',
    'inventory.noLocations': 'No storage locations found',
    'inventory.scanToView': 'Scan to view all items here',
    'inventory.viewLocation': 'View location',

    // ── Fuel ──
    'fuel.title': 'Fuel & Consumables',
    'fuel.subtitle': 'Track fuel, water and operational fluid levels',
    'fuel.addResource': 'Add Resource',
    'fuel.lowLevelAlerts': 'Low Level Alerts',
    'fuel.levelAlerts': 'Level Alerts',
    'fuel.allResourceTypes': 'All Resource Types',
    'fuel.dieselMain': 'Diesel (Main Engines)',
    'fuel.dieselGenerator': 'Diesel (Generator)',
    'fuel.gasolineMain': 'Gasoline (Main Engines)',
    'fuel.gasolineGenerator': 'Gasoline (Generator)',
    'fuel.freshWater': 'Fresh Water',
    'fuel.engineOil': 'Engine Oil',
    'fuel.hydraulicOil': 'Hydraulic Oil',
    'fuel.greyWater': 'Grey Water',
    'fuel.blackWater': 'Black Water',
    'fuel.other': 'Other',
    'fuel.resourceOverview': 'Resource Overview',
    'fuel.logHistory': 'Log History',
    'fuel.notFound': 'No resources found',
    'fuel.lastRefill': 'Last refill:',
    'fuel.lastUse': 'Last use:',
    'fuel.refill': 'Refill',
    'fuel.consume': 'Consume',
    'fuel.totalEntries': 'Total entries',
    'fuel.refills': 'Refills',
    'fuel.consumptionEvents': 'Consumption events',
    'fuel.totalRefillCost': 'Total refill cost',
    'fuel.noLogEntries': 'No log entries found',
    'fuel.resourceName': 'Resource Name',
    'fuel.resourceType': 'Resource Type',
    'fuel.capacity': 'Capacity',
    'fuel.currentLevel': 'Current Level',
    'fuel.lowLevelAlert': 'Low Level Alert',
    'fuel.addResourceBtn': 'Add Resource',
    'fuel.editResource': 'Edit Resource',
    'fuel.saveResource': 'Save Changes',
    'fuel.logEntry': 'Log Entry',
    'fuel.entryType': 'Entry Type',
    'fuel.refillType': 'Refill',
    'fuel.consumptionType': 'Consumption',
    'fuel.quantityLabel': 'Quantity',
    'fuel.pricePerUnit': 'Price per Unit (optional)',
    'fuel.totalCost': 'Total Cost',
    'fuel.currency': 'Currency',
    'fuel.supplierLabel': 'Supplier (optional)',
    'fuel.locationLabel': 'Location (optional)',
    'fuel.engineHours': 'Engine Hours (optional)',
    'fuel.logDate': 'Date',
    'fuel.loggedBy': 'Logged By',
    'fuel.saveEntry': 'Save Entry',

    // ── Costs ──
    'costs.title': 'Cost Overview',
    'costs.subtitle': 'Track and analyse vessel operational costs',
    'costs.addExpense': 'Add Expense',
    'costs.periodCosts': 'Period Costs',
    'costs.inventoryValue': 'Inventory Value',
    'costs.lastMonth': 'Last Month',
    'costs.last3Months': 'Last 3 Months',
    'costs.last6Months': 'Last 6 Months',
    'costs.lastYear': 'Last Year',
    'costs.allTime': 'All Time',
    'costs.fuelFluids': 'Fuel & Fluids',
    'costs.partsUsed': 'Parts Used',
    'costs.externalService': 'External Service',
    'costs.operational': 'Operational',
    'costs.totalPeriodCost': 'Total Period Cost',
    'costs.operationalExpenses': 'Operational Expenses',
    'costs.mooring': 'Mooring',
    'costs.electricity': 'Electricity',
    'costs.water': 'Water',
    'costs.internet': 'Internet / Connectivity',
    'costs.wasteDisposal': 'Waste Disposal',
    'costs.portFees': 'Port Fees',
    'costs.insurance': 'Insurance',
    'costs.otherExpense': 'Other',
    'costs.noOpExpenses': 'No operational expenses yet',
    'costs.opExpensesHint': 'Record mooring fees, utilities, insurance and other port costs',
    'costs.addFirstEntry': 'Add first entry',
    'costs.fuelCostsTitle': 'Fuel & Fluids Costs',
    'costs.fuelCostsHint': 'Refill entries with recorded cost from the Fuel module',
    'costs.partsConsumedTitle': 'Parts Consumed in Maintenance',
    'costs.partsConsumedHint': 'Parts deducted from stock when completing maintenance tasks',
    'costs.externalServiceTitle': 'External Service Costs',
    'costs.externalServiceHint': 'Cost of external technicians recorded when completing maintenance tasks',
    'costs.noCostsRecorded': 'No costs recorded for this period',
    'costs.noCostsHint': 'Add an expense or log fuel refills with a cost to get started',
    'costs.totalStockValue': 'Total Stock Value',
    'costs.spareParts': 'Spare Parts',
    'costs.consumables': 'Consumables',
    'costs.totalInventoryValue': 'Total Onboard Inventory Value',
    'costs.itemsWithUnitCost': 'items with unit cost assigned',
    'costs.sparePart': 'Spare Part',
    'costs.consumable': 'Consumable',
    'costs.total': 'Total',
    'costs.noInventoryWithCost': 'No inventory items with unit cost',
    'costs.setUnitCostHint': 'Set a unit cost on your inventory items to see their value here',
    'costs.itemsByValue': 'Items by Value',
    'costs.unitCost': 'Unit Cost',
    'costs.stock': 'Stock',
    'costs.vesselValue': 'Vessel Value',
    'costs.addExpenseTitle': 'Add Operational Expense',
    'costs.category': 'Category',
    'costs.amount': 'Amount',
    'costs.expenseDate': 'Date',

    // ── History ──
    'history.title': 'Maintenance History',
    'history.subtitle': 'Complete audit trail of all maintenance activities',
    'history.search': 'Search history...',
    'history.allTime': 'All Time',
    'history.lastWeek': 'Last Week',
    'history.lastMonth': 'Last Month',
    'history.lastQuarter': 'Last Quarter',
    'history.lastYear': 'Last Year',
    'history.showing': 'Showing',
    'history.record': 'record',
    'history.records': 'records',
    'history.notFound': 'No maintenance history found',
    'history.equipmentLabel': 'Equipment:',
    'history.vesselLabel': 'Vessel:',
    'history.dueDate': 'Due Date',
    'history.completed': 'Completed',
    'history.completedBy': 'Completed By',
    'history.comments': 'Comments:',
    'history.partsUsed': 'Parts Used:',
    'history.issuesDetected': 'Issues Detected:',

    // ── Manuals ──
    'manuals.title': 'Documents',
    'manuals.subtitle': 'Vessel documents, manuals, clearances and crew records',
    'manuals.upload': 'Upload Document',
    'manuals.totalManuals': 'Total Documents',
    'manuals.vesselsCovered': 'Vessels Covered',
    'manuals.equipmentLinked': 'Equipment Linked',
    'manuals.search': 'Search documents...',
    'manuals.allEquipment': 'All Equipment',
    'manuals.showing': 'Showing',
    'manuals.manual': 'document',
    'manuals.manuals': 'documents',
    'manuals.notFound': 'No documents found',
    'manuals.adjustFilters': 'Try adjusting your filters',
    'manuals.uploadFirst': 'Upload your first document to get started',
    'manuals.deleteManual': 'Delete document',
    'manuals.uploadTitle': 'Upload Document',
    'manuals.manualTitle': 'Document Title',
    'manuals.manualDesc': 'Description (optional)',
    'manuals.selectEquipment': 'Select Equipment',
    'manuals.selectFile': 'Select File',
    'manuals.uploadBtn': 'Upload Document',
    'manuals.allCategories': 'All',
    'manuals.category': 'Category',
    'manuals.catManuals': 'Manuals',
    'manuals.catClearances': 'Clearances',
    'manuals.catCrewGuest': 'Crew & Guest',
    'manuals.catVesselDocs': 'Vessel Docs',

    // ── Users ──
    'users.accessDenied': 'Access Denied',
    'users.adminOnly': 'This page is only accessible to Administrators',
    'users.backToCustomers': 'Back to Customers',
    'users.manageUsers': 'Manage Users',
    'users.customerUsers': 'Users belonging to this customer account',
    'users.managementTitle': 'User Management',
    'users.managementSubtitle': 'Manage users and access permissions',
    'users.masterAdminAccess': 'Master Admin Access',
    'users.addUser': 'Add User',
    'users.search': 'Search users...',
    'users.allRoles': 'All Roles',
    'users.admin': 'Admin',
    'users.user': 'User',
    'users.loading': 'Loading users...',
    'users.errorLoading': 'Error Loading Users',
    'users.notFound': 'No users found',
    'users.masterAdmin': 'Master Admin',
    'users.deleteUser': 'Delete User',
    'users.deleteConfirm': 'Are you sure you want to delete',
    'users.deleteWarning': 'This action cannot be undone.',
    'users.role': 'Role',
    'users.fullName': 'Full Name',
    'users.emailAddress': 'Email Address',
    'users.phoneNumber': 'Phone Number',
    'users.assignedVessels': 'Assigned Vessels',
    'users.addUserTitle': 'Add User',
    'users.editUserTitle': 'Edit User',
    'users.saveUser': 'Save User',
    'users.createUser': 'Create User',

    // ── Customers ──
    'customers.title': 'Customer Management',
    'customers.subtitle': 'Manage customer accounts and subscriptions',
    'customers.addCustomer': 'Add Customer',
    'customers.masterAdminOnly': 'Master Admin Only',
    'customers.totalCustomers': 'Total Customers',
    'customers.activeSubscriptions': 'Active Subscriptions',
    'customers.trialAccounts': 'Trial Accounts',
    'customers.inactiveAccounts': 'Inactive Accounts',
    'customers.search': 'Search customers...',
    'customers.allStatus': 'All Status',
    'customers.active': 'Active',
    'customers.trial': 'Trial',
    'customers.inactive': 'Inactive',
    'customers.loading': 'Loading customers...',
    'customers.errorLoading': 'Error Loading Customers',
    'customers.notFound': 'No customers found',
    'customers.addFirst': 'Add Your First Customer',
    'customers.contactPerson': 'Contact Person',
    'customers.renewalDate': 'Renewal Date',
    'customers.vessels': 'Vessels',
    'customers.users': 'Users',
    'customers.viewVessels': 'View Vessels',
    'customers.manageUsers': 'Manage Users',
    'customers.setupService': 'Setup Service',
    'customers.grossTonnage': 'Gross Tonnage',
    'customers.customerName': 'Customer Name',
    'customers.contactName': 'Contact Name',
    'customers.contactEmail': 'Contact Email',
    'customers.contactPhone': 'Contact Phone',
    'customers.subscriptionStatus': 'Subscription Status',
    'customers.vesselLimit': 'Vessel Limit',
    'customers.notes': 'Notes',
    'customers.addCustomerTitle': 'Add Customer',
    'customers.editCustomerTitle': 'Edit Customer',

    // ── Settings ──
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and preferences',
    'settings.profile': 'Profile',
    'settings.fullName': 'Full Name',
    'settings.emailAddress': 'Email Address',
    'settings.phoneNumber': 'Phone Number',
    'settings.role': 'Role',
    'settings.language': 'Language',
    'settings.selectLanguage': 'Select Language',
    'settings.english': 'English',
    'settings.spanish': 'Español',
    'settings.security': 'Security',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm New Password',
    'settings.updatePassword': 'Update Password',
    'settings.notifications': 'Notifications',
    'settings.emailOverdue': 'Email notifications for overdue tasks',
    'settings.emailLowStock': 'Email notifications for low stock items',
    'settings.dailySummary': 'Daily maintenance summary',
    'settings.weeklyInventory': 'Weekly inventory report',
    'settings.companyDetails': 'Company Details',
    'settings.companyName': 'Company Name',
    'settings.subscriptionStatus': 'Subscription Status',
    'settings.renewalDate': 'Renewal Date',
    'settings.assignedVessels': 'Assigned Vessels',
    'settings.supportHint': 'Contact our support team for assistance with your account or platform features',
    'settings.save': 'Save Changes',
    'settings.masterAdmin': 'Master Admin',
    'settings.admin': 'Admin',
    'settings.user': 'User',

    // ── LocationView ──
    'location.storageLocation': 'Storage Location',
    'location.items': 'items',
    'location.itemNeedsRestock': 'item needs',
    'location.itemsNeedRestock': 'items need',
    'location.restockingHere': 'restocking here',
    'location.noItems': 'No items at this location',
    'location.noItemsHint': 'Check the location name or add items in Inventory',
    'location.addStock': 'Add Stock',
    'location.recordUsage': 'Record Usage',
    'location.minLabel': 'Min:',
    'location.updatedLabel': 'Updated',
    'location.receivedShipment': 'Received new shipment...',
    'location.usedDuringMaintenance': 'Used during engine maintenance...',

    // ── Nautius Chat ──
    'chat.title': 'Nautius',
    'chat.subtitle': 'AI Marine Assistant',
    'chat.buttonTitle': 'Ask Nautius',
    'chat.placeholder': 'Ask about maintenance, systems, manuals...',
    'chat.greetingCrew': 'Hello{name}! I have access to {count} {plural}{vessel}. Ask me anything about maintenance, troubleshooting or vessel systems.',
    'chat.greetingOwner': 'Hello{name}! I\'m Nautius, your onboard AI assistant. How can I help you today?',
    'chat.suggest.oilChange': 'When is the oil change due?',
    'chat.suggest.generator': 'Generator maintenance checklist',
    'chat.suggest.schedule': 'Show pending maintenance',
    'chat.suggest.engineNoise': 'Strange engine noise',
    'chat.suggest.smell': 'Fuel smell onboard',
    'chat.suggest.departure': 'Pre-departure checklist',
    'chat.genericError': 'I couldn\'t process your request. Please try again.',
    'chat.connectionError': 'Connection error. Please check your internet and try again.',
    'chat.notConfigured': 'Nautius is not configured yet. Please contact support.',
  },

  es: {
    // ── Navegación ──
    'nav.dashboard': 'Panel',
    'nav.fleetOverview': 'Vista de Flota',
    'nav.vessels': 'Embarcaciones',
    'nav.equipment': 'Equipos',
    'nav.waterToys': 'Water Toys',
    'nav.maintenance': 'Mantenimiento',
    'nav.inventory': 'Inventario',
    'nav.manuals': 'Manuales',
    'nav.history': 'Historial',
    'nav.customers': 'Clientes',
    'nav.users': 'Usuarios',
    'nav.fuel': 'Combustible',
    'nav.costs': 'Costes',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar sesión',
    'nav.needHelp': '¿Necesitas ayuda?',
    'nav.contactSupport': 'Contacta con soporte',
    'nav.close': 'Cerrar menú',
    'nav.onboardingSubmissions': 'Solicitudes',
    'nav.crew': 'Tripulación',
    'nav.guestList': 'Lista de Invitados',
    'nav.procurement': 'Compras',

    // ── Encabezado ──
    'header.toggleMenu': 'Alternar menú',
    'header.switchVessel': 'Cambiar embarcación',
    'header.notifications': 'Notificaciones',
    'header.logout': 'Cerrar sesión',

    // ── Login ──
    'login.subtitle': 'Suite de Ingeniería',
    'login.welcome': 'Bienvenido',
    'login.email': 'Correo electrónico',
    'login.emailPlaceholder': 'Introduce tu correo',
    'login.password': 'Contraseña',
    'login.passwordPlaceholder': 'Introduce tu contraseña',
    'login.invalidCredentials': 'Correo o contraseña incorrectos',
    'login.error': 'Se produjo un error. Por favor, inténtalo de nuevo.',
    'login.signIn': 'Iniciar sesión',
    'login.signingIn': 'Iniciando sesión...',
    'login.demoAccounts': 'Cuentas de demostración',
    'login.masterAdmin': 'Administrador Master',
    'login.customerAdmin': 'Administrador de cliente',
    'login.engineer': 'Ingeniero',
    'login.demoPassword': 'Contraseña: demo123',

    // ── Común ──
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.search': 'Buscar...',
    'common.add': 'Añadir',
    'common.confirm': 'Confirmar',
    'common.close': 'Cerrar',
    'common.upload': 'Subir',
    'common.download': 'Descargar',
    'common.open': 'Abrir',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.tryAgain': 'Intentar de nuevo',
    'common.saveChanges': 'Guardar cambios',
    'common.noResults': 'Sin resultados',
    'common.showing': 'Mostrando',
    'common.filters': 'Filtros',
    'common.allVessels': 'Todas las embarcaciones',
    'common.allDepartments': 'Todos los departamentos',
    'common.vessel': 'Embarcación',
    'common.equipment': 'Equipo',
    'common.actions': 'Acciones',
    'common.name': 'Nombre',
    'common.type': 'Tipo',
    'common.status': 'Estado',
    'common.notes': 'Notas',
    'common.description': 'Descripción',
    'common.date': 'Fecha',
    'common.by': 'Por',
    'common.unknown': 'Desconocido',
    'common.operational': 'Operativo',
    'common.critical': 'Crítico',
    'common.high': 'Alta',
    'common.medium': 'Media',
    'common.low': 'Baja',
    'common.active': 'Activo',
    'common.inactive': 'Inactivo',
    'common.you': 'Tú',
    'common.exportPDF': 'Exportar PDF',
    'common.noFile': 'Sin archivo',
    'common.photos': 'Fotos',
    'common.quantity': 'Cantidad',
    'common.reason': 'Motivo',
    'common.supplier': 'Proveedor',
    'common.location': 'Ubicación',
    'common.unit': 'Unidad',
    'common.email': 'Correo electrónico',
    'common.phone': 'Teléfono',
    'common.contactSupport': 'Contactar soporte',
    'common.needHelp': '¿Necesitas ayuda?',
    'common.noData': 'Sin datos disponibles',

    // ── Panel ──
    'dashboard.title': 'Panel de control',
    'dashboard.masterTitle': 'Panel del Administrador Master',
    'dashboard.masterSubtitle': 'Resumen de la plataforma y gestión de clientes',
    'dashboard.masterAdmin': 'Administrador Master',
    'dashboard.totalCustomers': 'Total de clientes',
    'dashboard.activeSubscriptions': 'Suscripciones activas',
    'dashboard.inTrial': 'en prueba',
    'dashboard.trialAccounts': 'Cuentas de prueba',
    'dashboard.pendingConversion': 'Conversión pendiente',
    'dashboard.inactiveAccounts': 'Cuentas inactivas',
    'dashboard.churned': 'Canceladas',
    'dashboard.allAccounts': 'Todas las cuentas',
    'dashboard.recentCustomers': 'Clientes recientes',
    'dashboard.viewAllCustomers': 'Ver todos los clientes',
    'dashboard.noCustomersYet': 'Aún no hay clientes',
    'dashboard.addFirstCustomer': 'Añadir primer cliente',
    'dashboard.quickActions': 'Acciones rápidas',
    'dashboard.managePlatform': 'Gestiona tu plataforma eficientemente',
    'dashboard.addNewCustomer': 'Añadir nuevo cliente',
    'dashboard.createUserAccount': 'Crear cuenta de usuario',
    'dashboard.platformInfo': 'Información de la plataforma',
    'dashboard.systemOverview': 'Resumen del sistema',
    'dashboard.platformStatus': 'Estado de la plataforma',
    'dashboard.customerRetention': 'Retención de clientes',
    'dashboard.vesselLimit': 'Límite de embarcaciones',
    'dashboard.vesselStatus': 'Estado de embarcaciones',
    'dashboard.maintenance': 'Mantenimiento',
    'dashboard.inventory': 'Inventario',
    'dashboard.attentionNeeded': 'Atención requerida',
    'dashboard.actionRequired': 'ACCIÓN REQUERIDA',
    'dashboard.due48h': 'Vence en 48h',
    'dashboard.outStock': 'Sin stock',
    'dashboard.resolveNow': 'Resolver ahora',
    'dashboard.overdueTasks': 'Tareas vencidas',
    'dashboard.dueSoon': 'Próximas',
    'dashboard.upcoming': 'Programadas',
    'dashboard.lowStockItems': 'Artículos con stock bajo',
    'dashboard.reorderNeeded': 'Reabastecimiento necesario',
    'dashboard.allCaughtUp': '¡Todo al día!',
    'dashboard.urgentMaintenance': 'Mantenimiento urgente',
    'dashboard.viewAll': 'Ver todo',
    'dashboard.lowStockAlerts': 'Alertas de stock bajo',
    'dashboard.allItemsInStock': 'Todos los artículos en stock',
    'dashboard.recentActivity': 'Actividad reciente',
    'dashboard.noRecentActivity': 'Sin actividad reciente',
    'dashboard.overview': 'Resumen de flota',
    'dashboard.totalVessels': 'Total embarcaciones',
    'dashboard.activeVessels': 'Embarcaciones activas',
    'dashboard.underMaintenance': 'En mantenimiento',
    'dashboard.docked': 'Atracadas',
    'dashboard.upcomingMaintenance': 'Mantenimiento próximo',
    'dashboard.dueDate': 'Fecha de vencimiento',

    // ── Embarcaciones ──
    'vessels.title': 'Gestión de embarcaciones',
    'vessels.subtitle': 'Gestiona las embarcaciones de la flota',
    'vessels.addVessel': 'Añadir embarcación',
    'vessels.search': 'Buscar embarcaciones...',
    'vessels.allTypes': 'Todos los tipos',
    'vessels.loading': 'Cargando embarcaciones...',
    'vessels.errorLoading': 'Error al cargar embarcaciones',
    'vessels.notFound': 'No se encontraron embarcaciones',
    'vessels.createdWithCustomers': 'Las embarcaciones se crean al añadir clientes propietarios de yates',
    'vessels.adjustFilters': 'Ajusta tu búsqueda o filtros',
    'vessels.registrationId': 'Matrícula',
    'vessels.yearBuilt': 'Año de construcción',
    'vessels.loa': 'Eslora',
    'vessels.flag': 'Bandera',
    'vessels.name': 'Nombre',
    'vessels.type': 'Tipo',
    'vessels.captain': 'Capitán',
    'vessels.lastInspection': 'Última inspección',

    // ── Equipos ──
    'equipment.title': 'Gestión de equipos',
    'equipment.subtitle': 'Gestiona los equipos y sistemas de la embarcación',
    'equipment.addNew': 'Añadir equipo',
    'equipment.search': 'Buscar equipos...',
    'equipment.searchPlaceholder': 'Buscar por nombre, tipo, fabricante...',
    'equipment.allTypes': 'Todos los tipos',
    'equipment.allManufacturers': 'Todos los fabricantes',
    'equipment.allVessels': 'Todas las embarcaciones',
    'equipment.showing': 'Mostrando',
    'equipment.item': 'elemento',
    'equipment.items': 'elementos',
    'equipment.editEquipment': 'Editar equipo',
    'equipment.name': 'Nombre del equipo',
    'equipment.type': 'Tipo',
    'equipment.manufacturer': 'Fabricante',
    'equipment.model': 'Modelo',
    'equipment.serialNumber': 'Número de serie',
    'equipment.location': 'Ubicación',
    'equipment.vessel': 'Embarcación',
    'equipment.notFound': 'No se encontraron equipos',
    'equipment.adjustFilters': 'Ajusta tus filtros',
    'equipment.installationDate': 'Fecha de instalación',
    'equipment.specifications': 'Especificaciones',
    'equipment.addEquipment': 'Añadir equipo',
    'equipment.lastMaintenance': 'Último mantenimiento',
    'equipment.noEquipment': 'No se encontraron equipos',
    'equipment.noEquipmentDesc': 'Añade equipos para comenzar a gestionar los sistemas de tu embarcación',
    'equipment.viewTasks': 'Ver tareas',
    'equipment.viewManuals': 'Ver manuales',
    'equipment.deleteTitle': 'Eliminar equipo',
    'equipment.deleteMessage': '¿Estás seguro de que deseas eliminar este equipo? Esta acción no se puede deshacer.',
    'equipment.editTitle': 'Editar equipo',
    'equipment.addTitle': 'Añadir equipo',
    'equipment.notes': 'Notas',
    'equipment.addHint': 'Completa los detalles para añadir este equipo a tu embarcación',

    // ── Mantenimiento ──
    'maintenance.title': 'Tareas de mantenimiento',
    'maintenance.subtitle': 'Gestiona el plan de mantenimiento preventivo',
    'maintenance.newTask': 'Nueva tarea',
    'maintenance.createTask': 'Crear nueva tarea de mantenimiento',
    'maintenance.search': 'Buscar tareas...',
    'maintenance.allStatus': 'Todos los estados',
    'maintenance.overdue': 'Vencida',
    'maintenance.dueSoon': 'Próxima',
    'maintenance.upcoming': 'Programada',
    'maintenance.completed': 'Completada',
    'maintenance.allPriorities': 'Todas las prioridades',
    'maintenance.allCategories': 'Todas las categorías',
    'maintenance.allVessels': 'Todas las embarcaciones',
    'maintenance.showing': 'Mostrando',
    'maintenance.task': 'tarea',
    'maintenance.tasks': 'tareas',
    'maintenance.notFound': 'No se encontraron tareas de mantenimiento',
    'maintenance.equipmentLabel': 'Equipo:',
    'maintenance.vesselLabel': 'Embarcación:',
    'maintenance.assignedLabel': 'Asignado:',
    'maintenance.dOverdue': 'd de retraso',
    'maintenance.dRemaining': 'd restantes',
    'maintenance.urgent': 'URGENTE',
    'maintenance.dueDate': 'Fecha de vencimiento',
    'maintenance.assignee': 'Asignado',
    'maintenance.priority': 'Prioridad',
    'maintenance.pending': 'Pendiente',
    'maintenance.inProgress': 'En progreso',
    'maintenance.all': 'Todas',
    'maintenance.taskTitle': 'Título de la tarea',
    'maintenance.taskTitlePlaceholder': 'Ej: Cambio de aceite motor principal',
    'maintenance.descriptionPlaceholder': 'Descripción detallada de la tarea de mantenimiento...',
    'maintenance.category': 'Categoría',
    'maintenance.categoryPlaceholder': 'Selecciona o escribe una categoría...',
    'maintenance.selectVessel': 'Seleccionar embarcación',
    'maintenance.selectEquipment': 'Seleccionar equipo',
    'maintenance.assignedTo': 'Asignado a',
    'maintenance.unassigned': 'Sin asignar',
    'maintenance.nextDueDate': 'Próxima fecha de vencimiento',
    'maintenance.recurrenceInterval': 'Intervalo de recurrencia',
    'maintenance.taskScheduleNote': 'Esta tarea se añadirá al plan de mantenimiento. Puedes editarla después desde el detalle de tarea.',
    'maintenance.createTask2': 'Crear tarea',
    'maintenance.noEquipment': 'Sin equipo',
    'maintenance.status': 'Estado',
    'maintenance.completeTask': 'Completar tarea',
    'maintenance.completedBy': 'Completado por',
    'maintenance.commentsLabel': 'Comentarios / Observaciones',
    'maintenance.commentsPlaceholder': 'Describe el trabajo realizado y cualquier observación...',
    'maintenance.issuesDetected': 'Problemas detectados (opcional)',
    'maintenance.issuesPlaceholder': 'Describe cualquier problema o inconveniente encontrado...',
    'maintenance.externalServiceCost': 'Coste de servicio externo (opcional)',
    'maintenance.externalServiceCostHint': 'Coste del técnico o proveedor externo, si aplica',
    'maintenance.partsUsed': 'Piezas y consumibles usados',
    'maintenance.addItem': 'Añadir elemento',
    'maintenance.noPartsAdded': 'No se añadieron piezas ni consumibles',
    'maintenance.available': 'Disponible:',
    'maintenance.exceedsStock': 'supera el stock',
    'maintenance.photoUploads': 'Subir fotos (opcional)',
    'maintenance.clickToAddPhotos': 'Haz clic para añadir fotos',
    'maintenance.photoFormats': 'PNG, JPG, WEBP hasta 10MB cada una',
    'maintenance.confirmCompletion': 'Confirmar finalización de tarea',
    'maintenance.confirmCompletionText': 'Confirmo que esta tarea de mantenimiento se ha completado satisfactoriamente. El stock se descontará automáticamente de',
    'maintenance.uploadingPhotos': 'Subiendo fotos...',
    'maintenance.completeTaskBtn': 'Completar tarea',

    // ── Inventario ──
    'inventory.title': 'Gestión de inventario',
    'inventory.subtitle': 'Control de repuestos y consumibles',
    'inventory.addItem': 'Añadir artículo',
    'inventory.allItems': 'Todos los artículos',
    'inventory.locationsQR': 'Ubicaciones y QR',
    'inventory.lowStockAlert': 'Alerta de stock bajo',
    'inventory.reorderRecommended': 'Reabastecimiento recomendado',
    'inventory.showAll': 'Mostrar todo',
    'inventory.viewLowStock': 'Ver stock bajo',
    'inventory.search': 'Buscar inventario...',
    'inventory.allTypes': 'Todos los tipos',
    'inventory.spareParts': 'Repuestos',
    'inventory.consumables': 'Consumibles',
    'inventory.allCategories': 'Todas las categorías',
    'inventory.showing': 'Mostrando',
    'inventory.item': 'artículo',
    'inventory.items': 'artículos',
    'inventory.itemName': 'Nombre del artículo',
    'inventory.partNumber': 'Número de pieza',
    'inventory.category': 'Categoría',
    'inventory.currentStock': 'Stock actual',
    'inventory.minStock': 'Stock mínimo',
    'inventory.lowStock': 'Stock bajo',
    'inventory.inStock': 'En stock',
    'inventory.adjust': 'Ajustar',
    'inventory.notFound': 'No se encontraron artículos',
    'inventory.unitOfMeasure': 'Unidad de medida',
    'inventory.unitCost': 'Coste unitario',
    'inventory.storageLocation': 'Ubicación de almacenamiento',
    'inventory.serialNumber': 'Número de serie',
    'inventory.sparePart': 'Repuesto',
    'inventory.consumable': 'Consumible',
    'inventory.quantity': 'Cantidad',
    'inventory.saveItem': 'Guardar artículo',
    'inventory.itemDetails': 'Detalles del artículo',
    'inventory.supplierInfo': 'Información del proveedor',
    'inventory.supplierName': 'Nombre del proveedor',
    'inventory.sendReorderRequest': 'Enviar solicitud de reabastecimiento',
    'inventory.stockMovementHistory': 'Historial de movimientos de stock',
    'inventory.stockAdded': 'Stock añadido',
    'inventory.stockRemoved': 'Stock retirado',
    'inventory.adjustment': 'Ajuste',
    'inventory.stockStatus': 'Estado del stock',
    'inventory.lowStockReorder': 'Stock bajo - Reabastecimiento necesario',
    'inventory.locationQR': 'QR de ubicación',
    'inventory.viewDetails': 'Ver detalles',
    'inventory.associatedEquipment': 'Equipo asociado',
    'inventory.quickActions': 'Acciones rápidas',
    'inventory.addStock': 'Añadir stock',
    'inventory.recordUsage': 'Registrar uso',
    'inventory.contactSupplier': 'Contactar proveedor',
    'inventory.adjustStock': 'Ajustar stock',
    'inventory.adjustmentType': 'Tipo de ajuste',
    'inventory.setLevel': 'Establecer',
    'inventory.newStockLevel': 'Nuevo nivel de stock',
    'inventory.storageLocations': 'Ubicaciones de almacenamiento',
    'inventory.locationSearch': 'Buscar ubicaciones...',
    'inventory.noLocations': 'No se encontraron ubicaciones',
    'inventory.scanToView': 'Escanea para ver todos los artículos aquí',
    'inventory.viewLocation': 'Ver ubicación',

    // ── Combustible ──
    'fuel.title': 'Combustible y consumibles',
    'fuel.subtitle': 'Controla niveles de combustible, agua y fluidos operativos',
    'fuel.addResource': 'Añadir recurso',
    'fuel.lowLevelAlerts': 'Alertas de nivel bajo',
    'fuel.levelAlerts': 'Alertas de Nivel',
    'fuel.allResourceTypes': 'Todos los tipos',
    'fuel.dieselMain': 'Diésel (Motores principales)',
    'fuel.dieselGenerator': 'Diésel (Generador)',
    'fuel.gasolineMain': 'Gasolina (Motores principales)',
    'fuel.gasolineGenerator': 'Gasolina (Generador)',
    'fuel.freshWater': 'Agua dulce',
    'fuel.engineOil': 'Aceite de motor',
    'fuel.hydraulicOil': 'Aceite hidráulico',
    'fuel.greyWater': 'Aguas grises',
    'fuel.blackWater': 'Aguas negras',
    'fuel.other': 'Otro',
    'fuel.resourceOverview': 'Resumen de recursos',
    'fuel.logHistory': 'Historial de registros',
    'fuel.notFound': 'No se encontraron recursos',
    'fuel.lastRefill': 'Último repostaje:',
    'fuel.lastUse': 'Último uso:',
    'fuel.refill': 'Repostar',
    'fuel.consume': 'Consumir',
    'fuel.totalEntries': 'Total de registros',
    'fuel.refills': 'Repostajes',
    'fuel.consumptionEvents': 'Consumos',
    'fuel.totalRefillCost': 'Coste total de repostajes',
    'fuel.noLogEntries': 'No se encontraron registros',
    'fuel.resourceName': 'Nombre del recurso',
    'fuel.resourceType': 'Tipo de recurso',
    'fuel.capacity': 'Capacidad',
    'fuel.currentLevel': 'Nivel actual',
    'fuel.lowLevelAlert': 'Alerta de nivel bajo',
    'fuel.addResourceBtn': 'Añadir recurso',
    'fuel.editResource': 'Editar recurso',
    'fuel.saveResource': 'Guardar cambios',
    'fuel.logEntry': 'Registrar entrada',
    'fuel.entryType': 'Tipo de entrada',
    'fuel.refillType': 'Repostaje',
    'fuel.consumptionType': 'Consumo',
    'fuel.quantityLabel': 'Cantidad',
    'fuel.pricePerUnit': 'Precio por unidad (opcional)',
    'fuel.totalCost': 'Coste total',
    'fuel.currency': 'Divisa',
    'fuel.supplierLabel': 'Proveedor (opcional)',
    'fuel.locationLabel': 'Ubicación (opcional)',
    'fuel.engineHours': 'Horas de motor (opcional)',
    'fuel.logDate': 'Fecha',
    'fuel.loggedBy': 'Registrado por',
    'fuel.saveEntry': 'Guardar registro',

    // ── Costes ──
    'costs.title': 'Resumen de costes',
    'costs.subtitle': 'Controla y analiza los costes operativos de la embarcación',
    'costs.addExpense': 'Añadir gasto',
    'costs.periodCosts': 'Costes del periodo',
    'costs.inventoryValue': 'Valor del inventario',
    'costs.lastMonth': 'Último mes',
    'costs.last3Months': 'Últimos 3 meses',
    'costs.last6Months': 'Últimos 6 meses',
    'costs.lastYear': 'Último año',
    'costs.allTime': 'Todo el tiempo',
    'costs.fuelFluids': 'Combustible y fluidos',
    'costs.partsUsed': 'Piezas usadas',
    'costs.externalService': 'Servicio externo',
    'costs.operational': 'Operativos',
    'costs.totalPeriodCost': 'Coste total del periodo',
    'costs.operationalExpenses': 'Gastos operativos',
    'costs.mooring': 'Amarre',
    'costs.electricity': 'Electricidad',
    'costs.water': 'Agua',
    'costs.internet': 'Internet / Conectividad',
    'costs.wasteDisposal': 'Gestión de residuos',
    'costs.portFees': 'Tasas portuarias',
    'costs.insurance': 'Seguro',
    'costs.otherExpense': 'Otro',
    'costs.noOpExpenses': 'Aún no hay gastos operativos',
    'costs.opExpensesHint': 'Registra amarre, servicios, seguros y otros costes portuarios',
    'costs.addFirstEntry': 'Añadir primer registro',
    'costs.fuelCostsTitle': 'Costes de combustible y fluidos',
    'costs.fuelCostsHint': 'Repostajes con coste registrado desde el módulo de combustible',
    'costs.partsConsumedTitle': 'Piezas consumidas en mantenimiento',
    'costs.partsConsumedHint': 'Piezas descontadas del stock al completar tareas de mantenimiento',
    'costs.externalServiceTitle': 'Costes de servicio externo',
    'costs.externalServiceHint': 'Coste de técnicos externos registrado al completar tareas de mantenimiento',
    'costs.noCostsRecorded': 'Sin costes registrados para este periodo',
    'costs.noCostsHint': 'Añade un gasto o registra repostajes con coste para empezar',
    'costs.totalStockValue': 'Valor total del stock',
    'costs.spareParts': 'Repuestos',
    'costs.consumables': 'Consumibles',
    'costs.totalInventoryValue': 'Valor total del inventario a bordo',
    'costs.itemsWithUnitCost': 'artículos con coste unitario asignado',
    'costs.sparePart': 'Repuesto',
    'costs.consumable': 'Consumible',
    'costs.total': 'Total',
    'costs.noInventoryWithCost': 'Sin artículos de inventario con coste unitario',
    'costs.setUnitCostHint': 'Asigna un coste unitario a tus artículos para ver su valor aquí',
    'costs.itemsByValue': 'Artículos por valor',
    'costs.unitCost': 'Coste unitario',
    'costs.stock': 'Stock',
    'costs.vesselValue': 'Valor por embarcación',
    'costs.addExpenseTitle': 'Añadir gasto operativo',
    'costs.category': 'Categoría',
    'costs.amount': 'Importe',
    'costs.expenseDate': 'Fecha',

    // ── Historial ──
    'history.title': 'Historial de mantenimiento',
    'history.subtitle': 'Registro completo de todas las actividades de mantenimiento',
    'history.search': 'Buscar historial...',
    'history.allTime': 'Todo el tiempo',
    'history.lastWeek': 'Última semana',
    'history.lastMonth': 'Último mes',
    'history.lastQuarter': 'Último trimestre',
    'history.lastYear': 'Último año',
    'history.showing': 'Mostrando',
    'history.record': 'registro',
    'history.records': 'registros',
    'history.notFound': 'No se encontró historial de mantenimiento',
    'history.equipmentLabel': 'Equipo:',
    'history.vesselLabel': 'Embarcación:',
    'history.dueDate': 'Fecha de vencimiento',
    'history.completed': 'Completado',
    'history.completedBy': 'Completado por',
    'history.comments': 'Comentarios:',
    'history.partsUsed': 'Piezas usadas:',
    'history.issuesDetected': 'Problemas detectados:',

    // ── Manuales ──
    'manuals.title': 'Documentos',
    'manuals.subtitle': 'Documentos del barco, manuales, despachos y registros de tripulación',
    'manuals.upload': 'Subir documento',
    'manuals.totalManuals': 'Total documentos',
    'manuals.vesselsCovered': 'Embarcaciones cubiertas',
    'manuals.equipmentLinked': 'Equipos vinculados',
    'manuals.search': 'Buscar documentos...',
    'manuals.allEquipment': 'Todos los equipos',
    'manuals.showing': 'Mostrando',
    'manuals.manual': 'documento',
    'manuals.manuals': 'documentos',
    'manuals.notFound': 'No se encontraron documentos',
    'manuals.adjustFilters': 'Ajusta tus filtros',
    'manuals.uploadFirst': 'Sube tu primer documento para empezar',
    'manuals.deleteManual': 'Eliminar documento',
    'manuals.uploadTitle': 'Subir documento',
    'manuals.manualTitle': 'Título del documento',
    'manuals.manualDesc': 'Descripción (opcional)',
    'manuals.selectEquipment': 'Seleccionar equipo',
    'manuals.selectFile': 'Seleccionar archivo',
    'manuals.uploadBtn': 'Subir documento',
    'manuals.allCategories': 'Todos',
    'manuals.category': 'Categoría',
    'manuals.catManuals': 'Manuales',
    'manuals.catClearances': 'Despachos',
    'manuals.catCrewGuest': 'Tripulación e Invitados',
    'manuals.catVesselDocs': 'Docs del Barco',

    // ── Usuarios ──
    'users.accessDenied': 'Acceso denegado',
    'users.adminOnly': 'Esta página solo es accesible para administradores',
    'users.backToCustomers': 'Volver a clientes',
    'users.manageUsers': 'Gestionar usuarios',
    'users.customerUsers': 'Usuarios de esta cuenta de cliente',
    'users.managementTitle': 'Gestión de usuarios',
    'users.managementSubtitle': 'Gestiona usuarios y permisos de acceso',
    'users.masterAdminAccess': 'Acceso de administrador master',
    'users.addUser': 'Añadir usuario',
    'users.search': 'Buscar usuarios...',
    'users.allRoles': 'Todos los roles',
    'users.admin': 'Administrador',
    'users.user': 'Usuario',
    'users.loading': 'Cargando usuarios...',
    'users.errorLoading': 'Error al cargar usuarios',
    'users.notFound': 'No se encontraron usuarios',
    'users.masterAdmin': 'Administrador Master',
    'users.deleteUser': 'Eliminar usuario',
    'users.deleteConfirm': '¿Estás seguro de que quieres eliminar',
    'users.deleteWarning': 'Esta acción no se puede deshacer.',
    'users.role': 'Rol',
    'users.fullName': 'Nombre completo',
    'users.emailAddress': 'Correo electrónico',
    'users.phoneNumber': 'Número de teléfono',
    'users.assignedVessels': 'Embarcaciones asignadas',
    'users.addUserTitle': 'Añadir usuario',
    'users.editUserTitle': 'Editar usuario',
    'users.saveUser': 'Guardar usuario',
    'users.createUser': 'Crear usuario',

    // ── Clientes ──
    'customers.title': 'Gestión de clientes',
    'customers.subtitle': 'Gestiona cuentas de clientes y suscripciones',
    'customers.addCustomer': 'Añadir cliente',
    'customers.masterAdminOnly': 'Solo Administrador Master',
    'customers.totalCustomers': 'Total de clientes',
    'customers.activeSubscriptions': 'Suscripciones activas',
    'customers.trialAccounts': 'Cuentas de prueba',
    'customers.inactiveAccounts': 'Cuentas inactivas',
    'customers.search': 'Buscar clientes...',
    'customers.allStatus': 'Todos los estados',
    'customers.active': 'Activo',
    'customers.trial': 'Prueba',
    'customers.inactive': 'Inactivo',
    'customers.loading': 'Cargando clientes...',
    'customers.errorLoading': 'Error al cargar clientes',
    'customers.notFound': 'No se encontraron clientes',
    'customers.addFirst': 'Añadir el primer cliente',
    'customers.contactPerson': 'Persona de contacto',
    'customers.renewalDate': 'Fecha de renovación',
    'customers.vessels': 'Embarcaciones',
    'customers.users': 'Usuarios',
    'customers.viewVessels': 'Ver embarcaciones',
    'customers.manageUsers': 'Gestionar usuarios',
    'customers.setupService': 'Configurar servicio',
    'customers.grossTonnage': 'Arqueo bruto',
    'customers.customerName': 'Nombre del cliente',
    'customers.contactName': 'Nombre de contacto',
    'customers.contactEmail': 'Correo de contacto',
    'customers.contactPhone': 'Teléfono de contacto',
    'customers.subscriptionStatus': 'Estado de suscripción',
    'customers.vesselLimit': 'Límite de embarcaciones',
    'customers.notes': 'Notas',
    'customers.addCustomerTitle': 'Añadir cliente',
    'customers.editCustomerTitle': 'Editar cliente',

    // ── Configuración ──
    'settings.title': 'Configuración',
    'settings.subtitle': 'Gestiona tu cuenta y preferencias',
    'settings.profile': 'Perfil',
    'settings.fullName': 'Nombre completo',
    'settings.emailAddress': 'Correo electrónico',
    'settings.phoneNumber': 'Número de teléfono',
    'settings.role': 'Rol',
    'settings.language': 'Idioma',
    'settings.selectLanguage': 'Seleccionar idioma',
    'settings.english': 'English',
    'settings.spanish': 'Español',
    'settings.security': 'Seguridad',
    'settings.currentPassword': 'Contraseña actual',
    'settings.newPassword': 'Nueva contraseña',
    'settings.confirmPassword': 'Confirmar nueva contraseña',
    'settings.updatePassword': 'Actualizar contraseña',
    'settings.notifications': 'Notificaciones',
    'settings.emailOverdue': 'Notificaciones por correo para tareas vencidas',
    'settings.emailLowStock': 'Notificaciones por correo para stock bajo',
    'settings.dailySummary': 'Resumen diario de mantenimiento',
    'settings.weeklyInventory': 'Informe semanal de inventario',
    'settings.companyDetails': 'Datos de la empresa',
    'settings.companyName': 'Nombre de la empresa',
    'settings.subscriptionStatus': 'Estado de suscripción',
    'settings.renewalDate': 'Fecha de renovación',
    'settings.assignedVessels': 'Embarcaciones asignadas',
    'settings.supportHint': 'Contacta con nuestro equipo de soporte para ayuda con tu cuenta',
    'settings.save': 'Guardar cambios',
    'settings.masterAdmin': 'Administrador Master',
    'settings.admin': 'Administrador',
    'settings.user': 'Usuario',

    // ── Vista de ubicación ──
    'location.storageLocation': 'Ubicación de almacenamiento',
    'location.items': 'artículos',
    'location.itemNeedsRestock': 'artículo necesita',
    'location.itemsNeedRestock': 'artículos necesitan',
    'location.restockingHere': 'reabastecimiento aquí',
    'location.noItems': 'No hay artículos en esta ubicación',
    'location.noItemsHint': 'Comprueba el nombre de la ubicación o añade artículos en Inventario',
    'location.addStock': 'Añadir stock',
    'location.recordUsage': 'Registrar uso',
    'location.minLabel': 'Mín:',
    'location.updatedLabel': 'Actualizado',
    'location.receivedShipment': 'Nuevo envío recibido...',
    'location.usedDuringMaintenance': 'Usado durante mantenimiento de motor...',

    // ── Nautius Chat ──
    'chat.title': 'Nautius',
    'chat.subtitle': 'Asistente marino IA',
    'chat.buttonTitle': 'Pregunta a Nautius',
    'chat.placeholder': 'Pregunta sobre mantenimiento, sistemas, manuales...',
    'chat.greetingCrew': '¡Hola{name}! Tengo acceso a {count} {plural}{vessel}. Pregúntame lo que necesites sobre mantenimiento, averías o sistemas de la embarcación.',
    'chat.greetingOwner': '¡Hola{name}! Soy Nautius, tu asistente IA a bordo. ¿En qué puedo ayudarte hoy?',
    'chat.suggest.oilChange': '¿Cuándo toca el cambio de aceite?',
    'chat.suggest.generator': 'Lista de mantenimiento del generador',
    'chat.suggest.schedule': 'Ver mantenimiento pendiente',
    'chat.suggest.engineNoise': 'Ruido extraño en el motor',
    'chat.suggest.smell': 'Olor a combustible a bordo',
    'chat.suggest.departure': 'Lista pre-salida',
    'chat.genericError': 'No pude procesar tu solicitud. Por favor, inténtalo de nuevo.',
    'chat.connectionError': 'Error de conexión. Comprueba tu internet e inténtalo de nuevo.',
    'chat.notConfigured': 'Nautius aún no está configurado. Contacta con soporte.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const stored = localStorage.getItem('nautium_language') as Language | null;
  const [language, setLanguageState] = useState<Language>(stored ?? 'en');
  const { user } = useAuth();

  useEffect(() => {
    if (user) {
      loadUserLanguage();
    }
  }, [user]);

  const loadUserLanguage = async () => {
    if (!user) return;
    const { data, error } = await supabase
      .from('user_profiles')
      .select('language')
      .eq('id', user.id)
      .maybeSingle();
    if (data && !error) {
      setLanguageState(data.language as Language);
      localStorage.setItem('nautium_language', data.language);
    }
  };

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('nautium_language', lang);
    if (user) {
      await supabase
        .from('user_profiles')
        .upsert({ id: user.id, language: lang, updated_at: new Date().toISOString() });
    }
  };

  const t = (key: string): string => {
    return translations[language][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
